### ISSUE TITLE
Run issue

### ISSUE THREAD

**Issue by ygjwd12345** [MendelXu/SAN#20]
Thanks for your wonderful work. When I run your code, I face the bug
'''
Traceback (most recent call last):
  File "/home/gyang/data/SAN/detectron2/detectron2/engine/train_loop.py", line 156, in train
    self.after_step()
  File "/home/gyang/data/SAN/detectron2/detectron2/engine/train_loop.py", line 190, in after_step
    h.after_step()
  File "/home/gyang/data/SAN/detectron2/detectron2/engine/hooks.py", line 556, in after_step
    self._do_eval()
  File "/home/gyang/data/SAN/detectron2/detectron2/engine/hooks.py", line 529, in _do_eval
    results = self._func()
  File "/home/gyang/data/SAN/detectron2/detectron2/engine/defaults.py", line 453, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/home/gyang/data/SAN/detectron2/detectron2/engine/defaults.py", line 602, in test
    data_loader = cls.build_test_loader(cfg, dataset_name)
  File "/home/gyang/data/SAN/train_net.py", line 102, in build_test_loader
    return build_detection_test_loader(cfg, dataset_name)
  File "/home/gyang/data/SAN/detectron2/detectron2/config/config.py", line 207, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/home/gyang/data/SAN/detectron2/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/gyang/data/SAN/san/data/build.py", line 268, in _test_loader_from_config
    dataset = get_detection_dataset_dicts(
  File "/home/gyang/data/SAN/san/data/build.py", line 129, in get_detection_dataset_dicts
    assert len(dicts), "Dataset '{}' is empty!".format(dataset_name)
AssertionError: Dataset 'pcontext_sem_seg_val' is empty!
'''
Would you mind helping me to fix this bug?

**Comment by MendelXu** [comment]
It seems the program couldn't find the dataset. Did you generate the pcontext dataset?

**Comment by ygjwd12345** [comment]
yes, following the guide. But I find the generate file name maybe is not correct.
the name something like
'''
pcontext
-train
-val
'''

**Comment by ygjwd12345** [comment]
I guess it should be
'''
pcontext
-pcontext_sem_seg_train
-pcontext_sem_seg_val
''' 
something like that?

**Comment by MendelXu** [comment]
> yes, following the guide. But I find the generate file name maybe is not correct. the name something like ''' pcontext -train -val '''

It it is organized like this, there should not . Have you confirmed that the directory is not empty?

![image](https://github.com/MendelXu/SAN/assets/44802022/154941f1-1fa7-48b3-b6db-0b66e80f3e4e)

**Comment by ygjwd12345** [comment]
I follow 
![image](https://github.com/MendelXu/SAN/assets/32895754/31c1cee7-e80d-4dea-b2a2-20c18c4470d2)
to build pcontext dataset.
I have confirmed the fold is not empty.

**Comment by ygjwd12345** [comment]
I fixed this bug. This issue is due to the file's format. The produced data is not consistent with code requirements.

**Comment by runhuzhao** [comment]
> 我修复了这个错误。此问题是由于文件的格式造成的。生成的数据与代码要求不一致。

哥，具体是啥原因啊，我也遇到了这个问题
