### ISSUE TITLE
Error on training: double free or corruption (!prev)

### ISSUE THREAD

**Issue by Solacex** [MendelXu/SAN#6]
Thanks for your inspiring work! 

When running the provided code, I met the following error. However, when I set num_workers=0, the code can run smoothly without and errors. 
Have you met this before? or do you have any idea to debug this? 

[04/05 09:08:31 d2.engine.train_loop]: [Starting training from iteration 0
*** Error in `/home/anaconda3/envs/guangrui_cuda11/bin/python': double free or corruption (!prev): 0x000055bbaca66830 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x733cf)[0x7f52abbfc3cf]
/lib64/libc.so.6(+0x78c3e)[0x7f52abc01c3e]
/lib64/libc.so.6(+0x79917)[0x7f52abc02917]
/lib64/ld-linux-x86-64.so.2(_dl_deallocate_tls+0x58)[0x7f52ac367588]
/lib64/libpthread.so.0(+0x71f7)[0x7f52abf3c1f7]
/lib64/libpthread.so.0(+0x730f)[0x7f52abf3c30f]
/lib64/libpthread.so.0(pthread_join+0xdb)[0x7f52abf3e65b]
/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(pthreadpool_destroy+0x82)[0x7f5247df80b2]
/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(+0x344abe7)[0x7f5245641be7]
/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(_ZN2at15set_num_threadsEi+0x38)[0x7f524397c3c8]
/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/torch/lib/libtorch_python.so(+0x5e9d3a)[0x7f52975a8d3a]
/home/anaconda3/envs/guangrui_cuda11/bin/python(+0x1401c5)[0x55bba920b1c5]
/home/anaconda3/envs/guangrui_cuda11/bin/python(+0xff58e)[0x55bba91ca58e]
/home/anaconda3/envs/guangrui_cuda11/bin/python(_PyFunction_Vectorcall+0x10b)[0x55bba925616b]
/home/anaconda3/envs/guangrui_cuda11/bin/python(PyVectorcall_Call+0x71)[0x55bba9207a41]
/home/anaconda3/envs/guangrui_cuda11/bin/python(_PyEval_EvalFrameDefault+0x207c)[0x55bba928e1dc]
/home/anaconda3/envs/guangrui_cuda11/bin/python(_PyFunction_Vectorcall+0x10b)[0x55bba925616b]
/home/anaconda3/envs/guangrui_cuda11/bin/python(+0xff56d)[0x55bba91ca56d]
/home/anaconda3/envs/guangrui_cuda11/bin/python(_PyEval_EvalCodeWithName+0x2d2)[0x55bba92552a2]
/home/anaconda3/envs/guangrui_cuda11/bin/python(_PyFunction_Vectorcall+0x1e3)[0x55bba9256243]
/home/anaconda3/envs/guangrui_cuda11/bin/python(+0xff56d)[0x55bba91ca56d]
/home/anaconda3/envs/guangrui_cuda11/bin/python(_PyFunction_Vectorcall+0x10b)[0x55bba925616b]
/home/anaconda3/envs/guangrui_cuda11/bin/python(+0xff819)[0x55bba91ca819]
/home/anaconda3/envs/guangrui_cuda11/bin/python(_PyEval_EvalCodeWithName+0x2d2)[0x55bba92552a2]
/home/anaconda3/envs/guangrui_cuda11/bin/python(_PyFunction_Vectorcall+0x1e3)[0x55bba925
6243]
/home/anaconda3/envs/guangrui_cuda11/bin/python(+0x10050b)[0x55bba91cb50b]
/home/anaconda3/envs/guangrui_cuda11/bin/python(_PyEval_EvalCodeWithName+0x2d2)[0x55bba92552a2]
/home/anaconda3/envs/guangrui_cuda11/bin/python(PyEval_EvalCodeEx+0x44)[0x55bba9256054]
/home/anaconda3/envs/guangrui_cuda11/bin/python(PyEval_EvalCode+0x1c)[0x55bba92e45bc]
/home/anaconda3/envs/guangrui_cuda11/bin/python(+0x219664)[0x55bba92e4664]
/home/anaconda3/envs/guangrui_cuda11/bin/python(+0x24b874)[0x55bba9316874]
/home/anaconda3/envs/guangrui_cuda11/bin/python(PyRun_StringFlags+0x7d)[0x55bba93190cd]
/home/anaconda3/envs/guangrui_cuda11/bin/python(PyRun_SimpleStringFlags+0x3f)[0x55bba91e0488]
/home/anaconda3/envs/guangrui_cuda11/bin/python(+0x11598b)[0x55bba91e098b]
/home/anaconda3/envs/guangrui_cuda11/bin/python(Py_BytesMain+0x39)[0x55bba9319389]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f52abbaaa85]
/home/anaconda3/envs/guangrui_cuda11/bin/python(+0x1de553)[0x55bba92a9553]
======= Memory map: ========

Skipping the memroy maps.... 

Traceback (most recent call last):
  File "train_net.py", line 281, in <module>
    launch(
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/detectron2/engine/launch.py", line 69, in launch
    mp.start_processes(
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1163, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 225138) is killed by signal: Aborted. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/detectron2/engine/launch.py", line 123, in _distributed_worker
    main_func(*args)
  File "/home/guangrui/san_ovSeg/train_net.py", line 275, in main
    return trainer.train()
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 155, in train
    self.run_step()
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 281, in run_step
    data = next(self._data_loader_iter)
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/detectron2/data/common.py", line 291, in __iter__
    for d in self.dataset:
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _next_data
    idx, data = self._get_data()
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1325, in _get_data
    success, data = self._try_get_data()
  File "/home/anaconda3/envs/guangrui_cuda11/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1176, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 225138, 225290) exited unexpectedly

**Comment by MendelXu** [comment]
I didn't meet the problem before. But according to your description, the job failed possibly because the shared memory was too small. Maybe you can try to increase it.

**Comment by Solacex** [comment]
My machine has ~36G shared memory, Is this enough for training?

**Comment by MendelXu** [comment]
I think it should be enough...Could you provide the original log file?

**Comment by Solacex** [comment]
The log is  https://gist.github.com/Solacex/77a44680da66ba0ea36ec881c03ee6ee, a very long error.

**Comment by Solacex** [comment]
Fine... I will try to look into it. It seems so wired..

**Comment by Solacex** [comment]
The bug still cannot be solved, and it bothers me a lot. Is it possible to share a conda environment with me (cuda11.3)?

**Comment by Solacex** [comment]
Hey this problem is solved through replacing mp.launch with torch.dist.launch, so I close this issue.
